### ISSUE TITLE
Bring up OPQ using Docker

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad-docker#2]
Follow the directions to bring up an instance of OPQ using https://openpowerquality.org/docs/cloud-docker.html

Write an essay in your professional portfolio documenting your experience and the issues you ran into, and whether you were successful or not. What did you learn about Docker in the process?

Post a link to your essay as a comment to this issue. And please post the link to #summer-startup in RadGrad2 Slack.

**Comment by calvan-liang** [comment]
Here is my essay on bringing up OPQ using Docker: https://calvan-liang.github.io/essays/opening-the-power-to-power-quality.html

**Comment by arslan-r** [comment]
Essay on OPQ 
https://arslan-r.github.io/essays/opq-with-docker.html
