### ISSUE TITLE
Add resource(s) to Resources page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad-docker#4]
Look for relevant readings, and add to https://radgrad.github.io/docs/devops/resources

This task will require you to download the RadGrad Summer 2020 docusaurus repo, edit the file, run the system locally to ensure your modifications are OK, then deploy it, as well as commit your changes to the docusaurus2 repo. See https://radgrad.github.io/docs/overview/managing-this-site

This task is not only helpful for generating additional useful resources, it's also  good for getting you ready to contribute documentation.  

When you're done, add a comment to this issue summarizing what resources you added.

**Comment by calvan-liang** [comment]
Added two resources. First resource is a link to a tutorial on how to install and use Docker Desktop on Windows through Windows Subsystem for Linux 2 (WSL 2). Both Arslan and I are using WSL 2 for Docker. Second resource is a link to sign up for Windows Insider. Currently, it is necessary to obtain Windows 10 Home 19018(+) to use Docker Desktop on Windows.

**Comment by arslan-r** [comment]
Added a few resources:

####Containerization for Beginners####

https://docker-curriculum.com/#hello-world
Docker Curriculum. Alternative Docker tutorial. Curriculum includes AWS integration.

https://www.youtube.com/watch?v=IbUXb4pQbPY&feature=youtu.be&t=75
Docker use example. TechLead discusses reasons why Docker is useful, how it can scale, and how he uses it in his projects.

https://kubernetes.io/docs/tutorials/kubernetes-basics/
Kubernetes basics. What is Kubernetes?

https://www.educative.io/blog/docker-kubernetes-beginners-guide
Kubernetes vs Docker. The difference between Docker and Kubernetes.
